### ISSUE TITLE
pipeline failing because of Document size cannot be larger than 5244928B. Current size: 5289542B and ##[error]Unable to find type [VstsTaskSdk.TerminationException].

### ISSUE THREAD

**Issue by vikasrathi1987** [azsk/ADOScanner-docs#78]
Hello,

The scanner was working fine, but the token was expired so we changed the token after that, we got the following error,

Sending scan report to extension storage
Scan result will be save with id: Phoenix_BuildId_259586_20-12-2023-11-27-15
{"$id":"1","innerException":null,"message":"Document size cannot be larger than 5244928B. Current size: 5289542B. ","typeName":"Microsoft.VisualStudio.Services.ExtensionManagement.WebApi.MaximumDocumentSizeException, Microsoft.VisualStudio.Services.ExtensionManagement.WebApi","typeKey":"MaximumDocumentSizeException","errorCode":0,"eventId":3000}
Cleaning logs from temp directory...
##[error]Unable to find type [VstsTaskSdk.TerminationException].
##[error]Exit code 1 returned from process: file name 'C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe', arguments '-NoLogo -Sta -NoProfile -NonInteractive -ExecutionPolicy Unrestricted -Command ". ([scriptblock]::Create('if ([Console]::InputEncoding -is [Text.UTF8Encoding] -and [Console]::InputEncoding.GetPreamble().Length -ne 0) { [Console]::InputEncoding = New-Object Text.UTF8Encoding $false } if (!$PSHOME) { $null = Get-Item -LiteralPath ''variable:PSHOME'' } else { Import-Module -Name ([System.IO.Path]::Combine($PSHOME, ''Modules\Microsoft.PowerShell.Management\Microsoft.PowerShell.Management.psd1'')) ; Import-Module -Name ([System.IO.Path]::Combine($PSHOME, ''Modules\Microsoft.PowerShell.Utility\Microsoft.PowerShell.Utility.psd1'')) }')) 2>&1 | ForEach-Object { Write-Verbose $_.Exception.Message -Verbose } ; Import-Module -Name 'c:\agents\1\_work\_tasks\ADOSecurityScanner_0f42e73b-1b51-41b9-8bd2-c1a864393316\1.5.7\ps_modules\VstsTaskSdk\VstsTaskSdk.psd1' -ArgumentList @{ NonInteractive = $true } -ErrorAction Stop ; $VerbosePreference = 'SilentlyContinue' ; $DebugPreference = 'SilentlyContinue' ; Invoke-VstsTaskScript -ScriptBlock ([scriptblock]::Create('. ''c:\agents\1\_work\_tasks\ADOSecurityScanner_0f42e73b-1b51-41b9-8bd2-c1a864393316\1.5.7\ADOSecurityScannerSVTRuntime.ps1'''))"'.
Finishing: ADO Security Scanner

**Comment by v-dpardeshi** [comment]
You encountered this error because it is a limitation of the ADO extension storage. However, to scan large projects and analyze the results, you can use our Continuous Assurance (CA) solution to obtain logs in Azure Log Analytics Workspace. Please refer to the link below for more information on the CA option.
[ADOScanner-docs/04-Running ADOScanner as Azure Function at master · azsk/ADOScanner-docs (github.com)](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fazsk%2FADOScanner-docs%2Ftree%2Fmaster%2F04-Running%2520ADOScanner%2520as%2520Azure%2520Function&data=05%7C01%7Cv-dpardeshi%40microsoft.com%7C6b187b16038541c5887208db8e71baa0%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C638260391359080741%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=nirqt4q8dXAn%2F3K0nvlZMkzeHrgo5vsAzy6nlXu30xA%3D&reserved=0)
